# Generated by Django 3.1.8 on 2021-04-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_status',
            field=models.BooleanField(default=True),
        ),
    ]
