# Generated by Django 3.1.8 on 2021-04-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pickup_days',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='specific_date',
            field=models.DateField(default=None),
        ),
    ]
