# Generated by Django 3.1.8 on 2021-04-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210408_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
